import type { UiIconName } from "./types";
import { isUiIconName } from "./registry";

/** Emoji / texto guardado en BD → icono SVG lineal McKenna. */
export const EMOJI_TO_ICON: Record<string, UiIconName> = {
  "🏰": "castle",
  "📍": "mapPin",
  "🏢": "building",
  "↳": "arrowSub",
  "🎯": "target",
  "📖": "book",
  "📋": "listChecks",
  "📚": "books",
  "📄": "file",
  "🔗": "link",
  "⚡": "lightning",
  "📌": "pin",
  "♾️": "infinity",
  "♾": "infinity",
  "🔔": "bell",
  "✅": "check",
  "✓": "check",
  "☑️": "check",
  "☑": "check",
  "🔒": "lock",
  "👤": "user",
  "👥": "users",
  "🎭": "users",
  "🏷️": "tag",
  "🏷": "tag",
  "📦": "package",
  "🔩": "nut",
  "🔧": "wrench",
  "🧪": "flask",
  "🤝": "handshake",
  "📜": "scroll",
  "💾": "floppyDisk",
  "🗑": "trash",
  "🗑️": "trash",
  "⏳": "hourglass",
  "⚔️": "sword",
  "⚔": "sword",
  "❌": "xCircle",
  "🚚": "truck",
  "📅": "calendar",
  "📆": "calendarBlank",
  "🗓️": "calendarDots",
  "🗓": "calendarDots",
  "🔄": "refresh",
  "📊": "chartBar",
  "🤖": "robot",
  "🔍": "search",
  "✉️": "envelope",
  "✉": "envelope",
  "🧾": "receipt",
  "👂": "ear",
  "🟢": "circle",
  "🔴": "circle",
  "🟡": "circle",
  "❓": "question",
  "⏰": "clock",
  "❗": "warning",
  "⚠️": "warning",
  "⚠": "warning",
  "✨": "sparkle",
  "✏️": "pencil",
  "✏": "pencil",
  "🏠": "home",
  "🛒": "cart",
  "🎙️": "mic",
  "🎙": "mic",
  "🏆": "trophy",
  "📥": "inbox",
  "📤": "outbox",
  "📎": "paperclip",
  "💬": "chat",
  "🛑": "stop",
  "📝": "note",
  "📷": "camera",
  "📁": "folder",
  "🖼": "image",
  "🖼️": "image",
  "🧱": "brick",
  "♻️": "recycle",
  "♻": "recycle",
  "🌅": "sunrise",
  "📱": "phone",
  "▶": "play",
  "▶️": "play",
  "🚀": "rocket",
  "👁": "eye",
  "👁️": "eye",
  "🎫": "ticket",
  "👋": "wave",
  "🔁": "refresh",
  "🔓": "unlock",
  "🖨": "printer",
  "🖨️": "printer",
  "▮▯▮": "barcode",
  "🔢": "listChecks",
  "🚩": "warning",
  "🗣": "chat",
  "🗣️": "chat",
  "👉": "arrowSub",
  "💎": "star",
  "🏛": "building",
  "🏛️": "building",
  "🔣": "barcode",
  "🌫️": "eye",
  "🌈": "palette",
  "🛫": "plane",
  "◻️": "package",
  "⚙️": "gear",
  "⚙": "gear",
  "🌐": "globe",
  "🌎": "globe",
  "🌍": "globe",
  "🪄": "sparkle",
  "🎉": "sparkle",
  "🛍️": "bag",
  "🛍": "bag",
  "🧴": "bottle",
  "⚗️": "flask",
  "⚗": "flask",
  "🥄": "spoon",
  "🛡️": "shield",
  "🛡": "shield",
  "🧩": "puzzle",
  "💡": "bulb",
  "💸": "coins",
  "💲": "coins",
  "💰": "coins",
  "💵": "coins",
  "📐": "ruler",
  "📏": "ruler",
  "🧭": "compass",
  "🌳": "tree",
  "⚖️": "scale",
  "⚖": "scale",
  "🙋": "hand",
  "✋": "hand",
  "🧹": "broom",
  "✍️": "pencil",
  "✍": "pencil",
  "🕐": "clock",
  "🕒": "clock",
  "⏱️": "clock",
  "⏱": "clock",
  "⏲️": "clock",
  "🎨": "palette",
  "🎬": "play",
  "📂": "folder",
  "🗂": "folder",
  "🗂️": "folder",
  "🖥️": "monitor",
  "🖥": "monitor",
  "💿": "floppyDisk",
  "📒": "book",
  "📔": "book",
  "📕": "book",
  "🔐": "lock",
  "🚨": "warning",
  "📣": "megaphone",
  "📢": "megaphone",
  "🚢": "ship",
  "✈️": "plane",
  "✈": "plane",
  "📞": "phone",
  "☎️": "phone",
  "🗺️": "mapPin",
  "🗺": "mapPin",
  "📡": "wave",
  "🩺": "eye",
  "🧮": "calculator",
  "🏦": "building",
  "🏭": "building",
  "🏪": "building",
  "📈": "chartBar",
  "📉": "chartBar",
  "💼": "package",
  "🎁": "package",
  "🧰": "wrench",
  "🔨": "wrench",
  "🛠️": "wrench",
  "🛠": "wrench",
  "⭐": "star",
  "🌟": "star",
  "👀": "eye",
  "💊": "flask",
  "🧫": "flask",
  "🔬": "flask",
  "🟠": "circle",
  "🔵": "circle",
  "⚪": "circle",
  "⚫": "circle",
  "📬": "envelope",
  "📧": "envelope",
  "📨": "envelope",
  "🧑": "user",
  "👨": "user",
  "👩": "user",
  "🤵": "user",
  "🧑‍💼": "user",
  "🔑": "lock",
  "📇": "listChecks",
  "🗒️": "note",
  "🗒": "note",
  "📃": "file",
  "📑": "file",
  "🗃️": "folder",
  "🗃": "folder",
  "🖊️": "pencil",
  "🖊": "pencil",
  "⏸️": "pause",
  "⏸": "pause",
  "⏹️": "stop",
  "⏹": "stop",
  "🔊": "megaphone",
  "🔈": "megaphone",
  "🎤": "mic",
  "🧠": "bulb",
  "🤔": "question",
  "ℹ️": "question",
  "🆕": "plus",
  "➕": "plus",
  "➖": "minus",
  "⬇️": "download",
  "⬇": "download",
  "💳": "receipt",
  "🧷": "paperclip",
  "🚛": "truck",
  "🛵": "truck",
  "🏍️": "truck",
};

/** Presets para elegir ícono de categoría / reino (valor guardado = emoji). */
export const TOPIC_ICON_PRESETS: { emoji: string; label: string }[] = [
  { emoji: "🏰", label: "Reino" },
  { emoji: "📋", label: "Lista" },
  { emoji: "🎯", label: "Misión" },
  { emoji: "📖", label: "Receta" },
  { emoji: "📦", label: "Inventario" },
  { emoji: "🔧", label: "Herramienta" },
  { emoji: "🧪", label: "Lab" },
  { emoji: "⚡", label: "Rápido" },
  { emoji: "🔔", label: "Alerta" },
  { emoji: "👤", label: "Persona" },
  { emoji: "🏢", label: "Depto" },
  { emoji: "🏷️", label: "Etiqueta" },
];

export function resolveTopicIcon(value?: string | null, fallback?: UiIconName): UiIconName | null {
  const v = (value ?? "").trim();
  if (!v) return fallback ?? null;
  if (v in EMOJI_TO_ICON) return EMOJI_TO_ICON[v];
  if (isUiIconName(v)) return v;
  const first = [...v][0];
  if (first && EMOJI_TO_ICON[first]) return EMOJI_TO_ICON[first];
  return fallback ?? null;
}
