import {
  ArrowBendDownRight,
  ArrowClockwise,
  ArrowsInSimple,
  ArrowsOutSimple,
  Bell,
  BookOpen,
  Books,
  Buildings,
  Calendar,
  CalendarBlank,
  CalendarDots,
  CaretDown,
  CastleTurret,
  ChartBar,
  ChatCircle,
  CheckCircle,
  Circle,
  ClipboardText,
  Clock,
  CornersOut,
  DotsSixVertical,
  Ear,
  Envelope,
  Flask,
  FloppyDisk,
  Funnel,
  Gear,
  GlobeHemisphereWest,
  GridFour,
  Handshake,
  Hourglass,
  Infinity,
  Lightning,
  Link,
  List,
  ListChecks,
  Lock,
  LockOpen,
  MagnifyingGlass,
  MapPin,
  Microphone,
  Moon,
  Nut,
  Package,
  PencilSimple,
  Plus,
  PushPin,
  Question,
  Receipt,
  Robot,
  Scroll,
  ShoppingCart,
  SignOut,
  SquaresFour,
  Sun,
  Star,
  Sword,
  Tag,
  Target,
  Trash,
  Truck,
  User,
  Users,
  WarningCircle,
  Wrench,
  X,
  XCircle,
  type Icon as PhosphorIcon,
} from "@phosphor-icons/react";
import type { Panel } from "../stores/app";
import type { UiIconName } from "./types";

/** Mapa panel del sidebar → Phosphor. Ver https://phosphoricons.com/ */
export const PANEL_ICON: Record<Panel, PhosphorIcon> = {
  dashboard: SquaresFour,
  chat: ChatCircle,
  voz: Microphone,
  webchat: GlobeHemisphereWest,
  preventa: Question,
  sync: ArrowClockwise,
  stock: Package,
  pedidos: ShoppingCart,
  facturas: Receipt,
  tickets: ClipboardText,
  settings: Gear,
};

/** Acciones y UI del panel / Centro de Mando. */
export const UI_ICON: Record<UiIconName, PhosphorIcon> = {
  signOut: SignOut,
  menu: List,
  refresh: ArrowClockwise,
  close: X,
  expand: ArrowsOutSimple,
  collapse: ArrowsInSimple,
  gridReset: GridFour,
  drag: DotsSixVertical,
  resize: CornersOut,
  sun: Sun,
  moon: Moon,
  pencil: PencilSimple,
  caretDown: CaretDown,
  castle: CastleTurret,
  mapPin: MapPin,
  building: Buildings,
  target: Target,
  book: BookOpen,
  warning: WarningCircle,
  check: CheckCircle,
  clock: Clock,
  sword: Sword,
  bell: Bell,
  xCircle: XCircle,
  plus: Plus,
  trash: Trash,
  funnel: Funnel,
  link: Link,
  lightning: Lightning,
  pin: PushPin,
  infinity: Infinity,
  lock: Lock,
  unlock: LockOpen,
  user: User,
  users: Users,
  tag: Tag,
  listChecks: ListChecks,
  wrench: Wrench,
  nut: Nut,
  books: Books,
  flask: Flask,
  handshake: Handshake,
  scroll: Scroll,
  floppyDisk: FloppyDisk,
  hourglass: Hourglass,
  truck: Truck,
  calendar: Calendar,
  calendarBlank: CalendarBlank,
  calendarDots: CalendarDots,
  chartBar: ChartBar,
  robot: Robot,
  search: MagnifyingGlass,
  envelope: Envelope,
  circle: Circle,
  arrowSub: ArrowBendDownRight,
  package: Package,
  receipt: Receipt,
  ear: Ear,
  question: Question,
  star: Star,
};

export function isUiIconName(v: string): v is UiIconName {
  return v in UI_ICON;
}

export function resolvePhosphorIcon(name: Panel | UiIconName): PhosphorIcon {
  if (name in PANEL_ICON) return PANEL_ICON[name as Panel];
  return UI_ICON[name as UiIconName];
}
