import type { SVGAttributes } from "react";
import type { MckIconWeight } from "./mck/types";
import type { Panel } from "../stores/app";

/** Iconos de acciones y UI compartidos (set McKenna SVG). */
export type UiIconName =
  | "signOut"
  | "menu"
  | "refresh"
  | "close"
  | "expand"
  | "collapse"
  | "gridReset"
  | "drag"
  | "resize"
  | "sun"
  | "moon"
  | "pencil"
  | "caretDown"
  | "castle"
  | "mapPin"
  | "building"
  | "target"
  | "book"
  | "warning"
  | "check"
  | "clock"
  | "sword"
  | "bell"
  | "xCircle"
  | "plus"
  | "minus"
  | "download"
  | "trash"
  | "funnel"
  | "link"
  | "lightning"
  | "pin"
  | "infinity"
  | "lock"
  | "unlock"
  | "user"
  | "users"
  | "tag"
  | "listChecks"
  | "wrench"
  | "nut"
  | "books"
  | "flask"
  | "handshake"
  | "scroll"
  | "floppyDisk"
  | "hourglass"
  | "truck"
  | "calendar"
  | "calendarBlank"
  | "calendarDots"
  | "chartBar"
  | "robot"
  | "search"
  | "envelope"
  | "circle"
  | "arrowSub"
  | "package"
  | "receipt"
  | "ear"
  | "question"
  | "star"
  | "calculator"
  | "file"
  | "home"
  | "mic"
  | "cart"
  | "inbox"
  | "outbox"
  | "paperclip"
  | "chat"
  | "stop"
  | "note"
  | "camera"
  | "folder"
  | "image"
  | "brick"
  | "recycle"
  | "sunrise"
  | "phone"
  | "play"
  | "pause"
  | "rocket"
  | "eye"
  | "ticket"
  | "wave"
  | "palette"
  | "monitor"
  | "megaphone"
  | "ship"
  | "plane"
  | "printer";

export type IconName = Panel | UiIconName;

export type IconWeight = MckIconWeight;

export interface IconProps extends Omit<SVGAttributes<SVGSVGElement>, "name"> {
  name: IconName;
  /** Tamaño en px (default 20). */
  size?: number;
  weight?: IconWeight;
}
